version: '3.4'
name: apigallery
services:
  api:
    image: apigallery
    container_name: apigallery-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
    networks:
      - apigallery
networks:
  apigallery:
    driver: bridge
